### PR TITLE
Change directory paths to be compatible with the streaming integrator

### LINKED ISSUE #52: Cannot deploy WSO2 Streaming Integrator image with different path
**Description:**
When deploying Streaming integrator, we observed a difference in the internal folder structure. 
Difference between siddhi runner paths and Streaming Integrator as follows.
execution file name - 
runner.sh -----------  streaming-integrator.sh

Home path - 
/home/siddhi_user/siddhi-runner/ -------------- /home/wso2carbon/wso2-streaming-integrator/

File persistence location - 
wso2/runner/siddhi-app-persistence ----- wso2/server/siddhi-app-persistence

**Affected Product Version:**
0.2.0-m1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
streaming integrator image - anugayan/streaming-integrator

### PR DESCRIPTION
**Pull request by BuddhiWathsala**
- path to the sh file = {SiddhiHome} + "bin/" + {SiddhiProfile} + ".sh"
- file persistence path = {SiddhiHome} + {SiddhiProfile} + "/siddhi-app-persistence"

## Automation tests
 - Unit tests 
   > Change artifacts_test.go and utils_test.go

### CODE REVIEW

File: pkg/controller/siddhiprocess/config.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ const (
 	MaxSurge                   int32  = 2
 	HealthPort                 int32  = 9090
 	ReadyPrPeriodSeconds       int32  = 20
-	ReadyPrInitialDelaySeconds int32  = 60
+	ReadyPrInitialDelaySeconds int32  = 40
```
Comment (pcnfernando) [inline pkg/controller/siddhiprocess/config.go]: Can you check whether we can decrease this initial delay more? Does this time includes the pulling time as well?

Comment (BuddhiWathsala) [reply pkg/controller/siddhiprocess/config.go]: Changed it. These change based on with trial and error method.

File: pkg/controller/siddhiprocess/artifacts_test.go [hunk 2]
```diff
@@ -189,7 +189,7 @@ func TestCreateDeployment(t *testing.T) {
 		configs.SiddhiImage,
 		"siddhirunner",
 		[]string{configs.Shell},
-		[]string{configs.SiddhiHome + configs.RunnerRPath},
+		[]string{configs.SiddhiHome + configs.SiddhiBin + "/" + configs.SiddhiProfile + ".sh"},
```
Comment (Mirage20) [inline pkg/controller/siddhiprocess/artifacts_test.go]: You can use `filepath` package to generate paths. https://golang.org/pkg/path/filepath/

File: pkg/controller/siddhiprocess/config.go [hunk 3]
```diff
@@ -81,10 +81,10 @@ const (
 	MaxUnavailable             int32  = 0
 	MaxSurge                   int32  = 2
 	HealthPort                 int32  = 9090
-	ReadyPrPeriodSeconds       int32  = 20
-	ReadyPrInitialDelaySeconds int32  = 60
-	LivePrPeriodSeconds        int32  = 120
-	LivePrInitialDelaySeconds  int32  = 120
+	ReadyPrPeriodSeconds       int32  = 10
```
Comment (Mirage20) [inline pkg/controller/siddhiprocess/config.go]: Do we need int32 here? Can't we just use int?

File: pkg/controller/siddhiprocess/config.go [hunk 4]
```diff
@@ -423,16 +423,20 @@ func (rsp *ReconcileSiddhiProcess) Configurations(sp *siddhiv1alpha2.SiddhiProce
 	configMap := &corev1.ConfigMap{}
 	err := rsp.client.Get(context.TODO(), types.NamespacedName{Name: cmName, Namespace: sp.Namespace}, configMap)
 	if err == nil {
-		if configMap.Data["siddhiRunnerHome"] != "" {
-			configs.SiddhiHome = configMap.Data["siddhiRunnerHome"]
+		if configMap.Data["siddhiHome"] != "" {
```
Comment (Mirage20) [inline pkg/controller/siddhiprocess/config.go]: You can use the 2nd value return by the map to check whether the key is available or not.
```go
if v, ok := configMap.Data["siddhiHome"] ; ok {
...
}
```

File: pkg/controller/siddhiprocess/artifacts_test.go (hunk 2 above)
Comment (BuddhiWathsala) [reply pkg/controller/siddhiprocess/artifacts_test.go]: Fixed in https://github.com/siddhi-io/siddhi-operator/pull/123/commits/785753fcea0dd5dcef62c63fe739e8e53b54e03e

File: pkg/controller/siddhiprocess/config.go (hunk 4 above)
Comment (BuddhiWathsala) [reply pkg/controller/siddhiprocess/config.go]: Fixed in https://github.com/siddhi-io/siddhi-operator/pull/123/commits/5a2fe203135ca70441588c95b228e415d49f3f8a

File: pkg/controller/siddhiprocess/config.go (hunk 3 above)
Comment (BuddhiWathsala) [reply pkg/controller/siddhiprocess/config.go]: Since K8s structs that uses this parameter need `int32`. If we use int we need to execute an unnecessary conversion step.
